-- ============================================================================
-- KHEEP v2 — Todas las comunas de Chile (16 regiones, 346 comunas)
-- ============================================================================
-- Hasta ahora solo existían las 5 comunas usadas para pruebas (todas de la
-- Región Metropolitana). El cliente pidió la lista real y completa del
-- país, para que el admin la administre (activar/desactivar) desde el
-- panel — nunca se crean/eliminan comunas desde la app, es una lista fija.
--
-- `on conflict (nombre) do update` deja esta migración segura de correr más
-- de una vez, y no duplica ni rompe las 5 comunas de prueba que ya existían
-- (les actualiza `region` si hiciera falta, sin tocar su `activa`).
-- ============================================================================

insert into public.comunas (nombre, region) values
  -- Región de Arica y Parinacota
  ('Arica', 'Región de Arica y Parinacota'),
  ('Camarones', 'Región de Arica y Parinacota'),
  ('Putre', 'Región de Arica y Parinacota'),
  ('General Lagos', 'Región de Arica y Parinacota'),

  -- Región de Tarapacá
  ('Iquique', 'Región de Tarapacá'),
  ('Alto Hospicio', 'Región de Tarapacá'),
  ('Pozo Almonte', 'Región de Tarapacá'),
  ('Camiña', 'Región de Tarapacá'),
  ('Colchane', 'Región de Tarapacá'),
  ('Huara', 'Región de Tarapacá'),
  ('Pica', 'Región de Tarapacá'),

  -- Región de Antofagasta
  ('Antofagasta', 'Región de Antofagasta'),
  ('Mejillones', 'Región de Antofagasta'),
  ('Sierra Gorda', 'Región de Antofagasta'),
  ('Taltal', 'Región de Antofagasta'),
  ('Calama', 'Región de Antofagasta'),
  ('Ollagüe', 'Región de Antofagasta'),
  ('San Pedro de Atacama', 'Región de Antofagasta'),
  ('Tocopilla', 'Región de Antofagasta'),
  ('María Elena', 'Región de Antofagasta'),

  -- Región de Atacama
  ('Copiapó', 'Región de Atacama'),
  ('Caldera', 'Región de Atacama'),
  ('Tierra Amarilla', 'Región de Atacama'),
  ('Chañaral', 'Región de Atacama'),
  ('Diego de Almagro', 'Región de Atacama'),
  ('Vallenar', 'Región de Atacama'),
  ('Alto del Carmen', 'Región de Atacama'),
  ('Freirina', 'Región de Atacama'),
  ('Huasco', 'Región de Atacama'),

  -- Región de Coquimbo
  ('La Serena', 'Región de Coquimbo'),
  ('Coquimbo', 'Región de Coquimbo'),
  ('Andacollo', 'Región de Coquimbo'),
  ('La Higuera', 'Región de Coquimbo'),
  ('Paiguano', 'Región de Coquimbo'),
  ('Vicuña', 'Región de Coquimbo'),
  ('Illapel', 'Región de Coquimbo'),
  ('Canela', 'Región de Coquimbo'),
  ('Los Vilos', 'Región de Coquimbo'),
  ('Salamanca', 'Región de Coquimbo'),
  ('Ovalle', 'Región de Coquimbo'),
  ('Combarbalá', 'Región de Coquimbo'),
  ('Monte Patria', 'Región de Coquimbo'),
  ('Punitaqui', 'Región de Coquimbo'),
  ('Río Hurtado', 'Región de Coquimbo'),

  -- Región de Valparaíso
  ('Valparaíso', 'Región de Valparaíso'),
  ('Casablanca', 'Región de Valparaíso'),
  ('Concón', 'Región de Valparaíso'),
  ('Juan Fernández', 'Región de Valparaíso'),
  ('Puchuncaví', 'Región de Valparaíso'),
  ('Quintero', 'Región de Valparaíso'),
  ('Viña del Mar', 'Región de Valparaíso'),
  ('Isla de Pascua', 'Región de Valparaíso'),
  ('Los Andes', 'Región de Valparaíso'),
  ('Calle Larga', 'Región de Valparaíso'),
  ('Rinconada', 'Región de Valparaíso'),
  ('San Esteban', 'Región de Valparaíso'),
  ('La Ligua', 'Región de Valparaíso'),
  ('Cabildo', 'Región de Valparaíso'),
  ('Papudo', 'Región de Valparaíso'),
  ('Petorca', 'Región de Valparaíso'),
  ('Zapallar', 'Región de Valparaíso'),
  ('Quillota', 'Región de Valparaíso'),
  ('La Calera', 'Región de Valparaíso'),
  ('Hijuelas', 'Región de Valparaíso'),
  ('La Cruz', 'Región de Valparaíso'),
  ('Nogales', 'Región de Valparaíso'),
  ('San Antonio', 'Región de Valparaíso'),
  ('Algarrobo', 'Región de Valparaíso'),
  ('Cartagena', 'Región de Valparaíso'),
  ('El Quisco', 'Región de Valparaíso'),
  ('El Tabo', 'Región de Valparaíso'),
  ('Santo Domingo', 'Región de Valparaíso'),
  ('San Felipe', 'Región de Valparaíso'),
  ('Catemu', 'Región de Valparaíso'),
  ('Llaillay', 'Región de Valparaíso'),
  ('Panquehue', 'Región de Valparaíso'),
  ('Putaendo', 'Región de Valparaíso'),
  ('Santa María', 'Región de Valparaíso'),
  ('Limache', 'Región de Valparaíso'),
  ('Olmué', 'Región de Valparaíso'),
  ('Villa Alemana', 'Región de Valparaíso'),
  ('Quilpué', 'Región de Valparaíso'),

  -- Región Metropolitana de Santiago
  ('Santiago', 'Región Metropolitana'),
  ('Cerrillos', 'Región Metropolitana'),
  ('Cerro Navia', 'Región Metropolitana'),
  ('Conchalí', 'Región Metropolitana'),
  ('El Bosque', 'Región Metropolitana'),
  ('Estación Central', 'Región Metropolitana'),
  ('Huechuraba', 'Región Metropolitana'),
  ('Independencia', 'Región Metropolitana'),
  ('La Cisterna', 'Región Metropolitana'),
  ('La Granja', 'Región Metropolitana'),
  ('La Pintana', 'Región Metropolitana'),
  ('La Reina', 'Región Metropolitana'),
  ('Las Condes', 'Región Metropolitana'),
  ('Lo Barnechea', 'Región Metropolitana'),
  ('Lo Espejo', 'Región Metropolitana'),
  ('Lo Prado', 'Región Metropolitana'),
  ('Macul', 'Región Metropolitana'),
  ('Pedro Aguirre Cerda', 'Región Metropolitana'),
  ('Peñalolén', 'Región Metropolitana'),
  ('Pudahuel', 'Región Metropolitana'),
  ('Quilicura', 'Región Metropolitana'),
  ('Quinta Normal', 'Región Metropolitana'),
  ('Recoleta', 'Región Metropolitana'),
  ('Renca', 'Región Metropolitana'),
  ('San Joaquín', 'Región Metropolitana'),
  ('San Ramón', 'Región Metropolitana'),
  ('Vitacura', 'Región Metropolitana'),
  ('Puente Alto', 'Región Metropolitana'),
  ('Pirque', 'Región Metropolitana'),
  ('San José de Maipo', 'Región Metropolitana'),
  ('Colina', 'Región Metropolitana'),
  ('Lampa', 'Región Metropolitana'),
  ('Tiltil', 'Región Metropolitana'),
  ('San Bernardo', 'Región Metropolitana'),
  ('Buin', 'Región Metropolitana'),
  ('Calera de Tango', 'Región Metropolitana'),
  ('Paine', 'Región Metropolitana'),
  ('Melipilla', 'Región Metropolitana'),
  ('Alhué', 'Región Metropolitana'),
  ('Curacaví', 'Región Metropolitana'),
  ('María Pinto', 'Región Metropolitana'),
  ('San Pedro', 'Región Metropolitana'),
  ('Talagante', 'Región Metropolitana'),
  ('El Monte', 'Región Metropolitana'),
  ('Isla de Maipo', 'Región Metropolitana'),
  ('Padre Hurtado', 'Región Metropolitana'),
  ('Peñaflor', 'Región Metropolitana'),

  -- Región del Libertador Bernardo O'Higgins
  ('Rancagua', 'Región del Libertador Bernardo O''Higgins'),
  ('Codegua', 'Región del Libertador Bernardo O''Higgins'),
  ('Coinco', 'Región del Libertador Bernardo O''Higgins'),
  ('Coltauco', 'Región del Libertador Bernardo O''Higgins'),
  ('Doñihue', 'Región del Libertador Bernardo O''Higgins'),
  ('Graneros', 'Región del Libertador Bernardo O''Higgins'),
  ('Las Cabras', 'Región del Libertador Bernardo O''Higgins'),
  ('Machalí', 'Región del Libertador Bernardo O''Higgins'),
  ('Malloa', 'Región del Libertador Bernardo O''Higgins'),
  ('Mostazal', 'Región del Libertador Bernardo O''Higgins'),
  ('Olivar', 'Región del Libertador Bernardo O''Higgins'),
  ('Peumo', 'Región del Libertador Bernardo O''Higgins'),
  ('Pichidegua', 'Región del Libertador Bernardo O''Higgins'),
  ('Quinta de Tilcoco', 'Región del Libertador Bernardo O''Higgins'),
  ('Rengo', 'Región del Libertador Bernardo O''Higgins'),
  ('Requínoa', 'Región del Libertador Bernardo O''Higgins'),
  ('San Vicente', 'Región del Libertador Bernardo O''Higgins'),
  ('Pichilemu', 'Región del Libertador Bernardo O''Higgins'),
  ('La Estrella', 'Región del Libertador Bernardo O''Higgins'),
  ('Litueche', 'Región del Libertador Bernardo O''Higgins'),
  ('Marchihue', 'Región del Libertador Bernardo O''Higgins'),
  ('Navidad', 'Región del Libertador Bernardo O''Higgins'),
  ('Paredones', 'Región del Libertador Bernardo O''Higgins'),
  ('San Fernando', 'Región del Libertador Bernardo O''Higgins'),
  ('Chépica', 'Región del Libertador Bernardo O''Higgins'),
  ('Chimbarongo', 'Región del Libertador Bernardo O''Higgins'),
  ('Lolol', 'Región del Libertador Bernardo O''Higgins'),
  ('Nancagua', 'Región del Libertador Bernardo O''Higgins'),
  ('Palmilla', 'Región del Libertador Bernardo O''Higgins'),
  ('Peralillo', 'Región del Libertador Bernardo O''Higgins'),
  ('Placilla', 'Región del Libertador Bernardo O''Higgins'),
  ('Pumanque', 'Región del Libertador Bernardo O''Higgins'),
  ('Santa Cruz', 'Región del Libertador Bernardo O''Higgins'),

  -- Región del Maule
  ('Talca', 'Región del Maule'),
  ('Constitución', 'Región del Maule'),
  ('Curepto', 'Región del Maule'),
  ('Empedrado', 'Región del Maule'),
  ('Maule', 'Región del Maule'),
  ('Pelarco', 'Región del Maule'),
  ('Pencahue', 'Región del Maule'),
  ('Río Claro', 'Región del Maule'),
  ('San Clemente', 'Región del Maule'),
  ('San Rafael', 'Región del Maule'),
  ('Cauquenes', 'Región del Maule'),
  ('Chanco', 'Región del Maule'),
  ('Pelluhue', 'Región del Maule'),
  ('Curicó', 'Región del Maule'),
  ('Hualañé', 'Región del Maule'),
  ('Licantén', 'Región del Maule'),
  ('Molina', 'Región del Maule'),
  ('Rauco', 'Región del Maule'),
  ('Romeral', 'Región del Maule'),
  ('Sagrada Familia', 'Región del Maule'),
  ('Teno', 'Región del Maule'),
  ('Vichuquén', 'Región del Maule'),
  ('Linares', 'Región del Maule'),
  ('Colbún', 'Región del Maule'),
  ('Longaví', 'Región del Maule'),
  ('Parral', 'Región del Maule'),
  ('Retiro', 'Región del Maule'),
  ('San Javier', 'Región del Maule'),
  ('Villa Alegre', 'Región del Maule'),
  ('Yerbas Buenas', 'Región del Maule'),

  -- Región de Ñuble
  ('Chillán', 'Región de Ñuble'),
  ('Bulnes', 'Región de Ñuble'),
  ('Cobquecura', 'Región de Ñuble'),
  ('Coelemu', 'Región de Ñuble'),
  ('Coihueco', 'Región de Ñuble'),
  ('Chillán Viejo', 'Región de Ñuble'),
  ('El Carmen', 'Región de Ñuble'),
  ('Ninhue', 'Región de Ñuble'),
  ('Ñiquén', 'Región de Ñuble'),
  ('Pemuco', 'Región de Ñuble'),
  ('Pinto', 'Región de Ñuble'),
  ('Portezuelo', 'Región de Ñuble'),
  ('Quillón', 'Región de Ñuble'),
  ('Quirihue', 'Región de Ñuble'),
  ('Ránquil', 'Región de Ñuble'),
  ('San Carlos', 'Región de Ñuble'),
  ('San Fabián', 'Región de Ñuble'),
  ('San Ignacio', 'Región de Ñuble'),
  ('San Nicolás', 'Región de Ñuble'),
  ('Treguaco', 'Región de Ñuble'),
  ('Yungay', 'Región de Ñuble'),

  -- Región del Biobío
  ('Concepción', 'Región del Biobío'),
  ('Coronel', 'Región del Biobío'),
  ('Chiguayante', 'Región del Biobío'),
  ('Florida', 'Región del Biobío'),
  ('Hualqui', 'Región del Biobío'),
  ('Lota', 'Región del Biobío'),
  ('Penco', 'Región del Biobío'),
  ('San Pedro de la Paz', 'Región del Biobío'),
  ('Santa Juana', 'Región del Biobío'),
  ('Talcahuano', 'Región del Biobío'),
  ('Tomé', 'Región del Biobío'),
  ('Hualpén', 'Región del Biobío'),
  ('Lebu', 'Región del Biobío'),
  ('Arauco', 'Región del Biobío'),
  ('Cañete', 'Región del Biobío'),
  ('Contulmo', 'Región del Biobío'),
  ('Curanilahue', 'Región del Biobío'),
  ('Los Álamos', 'Región del Biobío'),
  ('Tirúa', 'Región del Biobío'),
  ('Los Ángeles', 'Región del Biobío'),
  ('Antuco', 'Región del Biobío'),
  ('Cabrero', 'Región del Biobío'),
  ('Laja', 'Región del Biobío'),
  ('Mulchén', 'Región del Biobío'),
  ('Nacimiento', 'Región del Biobío'),
  ('Negrete', 'Región del Biobío'),
  ('Quilaco', 'Región del Biobío'),
  ('Quilleco', 'Región del Biobío'),
  ('San Rosendo', 'Región del Biobío'),
  ('Santa Bárbara', 'Región del Biobío'),
  ('Tucapel', 'Región del Biobío'),
  ('Yumbel', 'Región del Biobío'),
  ('Alto Biobío', 'Región del Biobío'),

  -- Región de la Araucanía
  ('Temuco', 'Región de la Araucanía'),
  ('Carahue', 'Región de la Araucanía'),
  ('Cunco', 'Región de la Araucanía'),
  ('Curarrehue', 'Región de la Araucanía'),
  ('Freire', 'Región de la Araucanía'),
  ('Galvarino', 'Región de la Araucanía'),
  ('Gorbea', 'Región de la Araucanía'),
  ('Lautaro', 'Región de la Araucanía'),
  ('Loncoche', 'Región de la Araucanía'),
  ('Melipeuco', 'Región de la Araucanía'),
  ('Nueva Imperial', 'Región de la Araucanía'),
  ('Padre las Casas', 'Región de la Araucanía'),
  ('Perquenco', 'Región de la Araucanía'),
  ('Pitrufquén', 'Región de la Araucanía'),
  ('Pucón', 'Región de la Araucanía'),
  ('Saavedra', 'Región de la Araucanía'),
  ('Teodoro Schmidt', 'Región de la Araucanía'),
  ('Toltén', 'Región de la Araucanía'),
  ('Vilcún', 'Región de la Araucanía'),
  ('Villarrica', 'Región de la Araucanía'),
  ('Cholchol', 'Región de la Araucanía'),
  ('Angol', 'Región de la Araucanía'),
  ('Collipulli', 'Región de la Araucanía'),
  ('Curacautín', 'Región de la Araucanía'),
  ('Ercilla', 'Región de la Araucanía'),
  ('Lonquimay', 'Región de la Araucanía'),
  ('Los Sauces', 'Región de la Araucanía'),
  ('Lumaco', 'Región de la Araucanía'),
  ('Purén', 'Región de la Araucanía'),
  ('Renaico', 'Región de la Araucanía'),
  ('Traiguén', 'Región de la Araucanía'),
  ('Victoria', 'Región de la Araucanía'),

  -- Región de Los Ríos
  ('Valdivia', 'Región de Los Ríos'),
  ('Corral', 'Región de Los Ríos'),
  ('Lanco', 'Región de Los Ríos'),
  ('Los Lagos', 'Región de Los Ríos'),
  ('Máfil', 'Región de Los Ríos'),
  ('Mariquina', 'Región de Los Ríos'),
  ('Paillaco', 'Región de Los Ríos'),
  ('Panguipulli', 'Región de Los Ríos'),
  ('La Unión', 'Región de Los Ríos'),
  ('Futrono', 'Región de Los Ríos'),
  ('Lago Ranco', 'Región de Los Ríos'),
  ('Río Bueno', 'Región de Los Ríos'),

  -- Región de Los Lagos
  ('Puerto Montt', 'Región de Los Lagos'),
  ('Calbuco', 'Región de Los Lagos'),
  ('Cochamó', 'Región de Los Lagos'),
  ('Fresia', 'Región de Los Lagos'),
  ('Frutillar', 'Región de Los Lagos'),
  ('Los Muermos', 'Región de Los Lagos'),
  ('Llanquihue', 'Región de Los Lagos'),
  ('Maullín', 'Región de Los Lagos'),
  ('Puerto Varas', 'Región de Los Lagos'),
  ('Castro', 'Región de Los Lagos'),
  ('Ancud', 'Región de Los Lagos'),
  ('Chonchi', 'Región de Los Lagos'),
  ('Curaco de Vélez', 'Región de Los Lagos'),
  ('Dalcahue', 'Región de Los Lagos'),
  ('Puqueldón', 'Región de Los Lagos'),
  ('Queilén', 'Región de Los Lagos'),
  ('Quellón', 'Región de Los Lagos'),
  ('Quemchi', 'Región de Los Lagos'),
  ('Quinchao', 'Región de Los Lagos'),
  ('Osorno', 'Región de Los Lagos'),
  ('Puerto Octay', 'Región de Los Lagos'),
  ('Purranque', 'Región de Los Lagos'),
  ('Puyehue', 'Región de Los Lagos'),
  ('Río Negro', 'Región de Los Lagos'),
  ('San Juan de la Costa', 'Región de Los Lagos'),
  ('San Pablo', 'Región de Los Lagos'),
  ('Chaitén', 'Región de Los Lagos'),
  ('Futaleufú', 'Región de Los Lagos'),
  ('Hualaihué', 'Región de Los Lagos'),
  ('Palena', 'Región de Los Lagos'),

  -- Región de Aysén
  ('Coyhaique', 'Región de Aysén'),
  ('Lago Verde', 'Región de Aysén'),
  ('Aysén', 'Región de Aysén'),
  ('Cisnes', 'Región de Aysén'),
  ('Guaitecas', 'Región de Aysén'),
  ('Cochrane', 'Región de Aysén'),
  ('O''Higgins', 'Región de Aysén'),
  ('Tortel', 'Región de Aysén'),
  ('Chile Chico', 'Región de Aysén'),
  ('Río Ibáñez', 'Región de Aysén'),

  -- Región de Magallanes y de la Antártica Chilena
  ('Punta Arenas', 'Región de Magallanes y de la Antártica Chilena'),
  ('Laguna Blanca', 'Región de Magallanes y de la Antártica Chilena'),
  ('Río Verde', 'Región de Magallanes y de la Antártica Chilena'),
  ('San Gregorio', 'Región de Magallanes y de la Antártica Chilena'),
  ('Cabo de Hornos', 'Región de Magallanes y de la Antártica Chilena'),
  ('Antártica', 'Región de Magallanes y de la Antártica Chilena'),
  ('Porvenir', 'Región de Magallanes y de la Antártica Chilena'),
  ('Primavera', 'Región de Magallanes y de la Antártica Chilena'),
  ('Timaukel', 'Región de Magallanes y de la Antártica Chilena'),
  ('Natales', 'Región de Magallanes y de la Antártica Chilena'),
  ('Torres del Paine', 'Región de Magallanes y de la Antártica Chilena')

on conflict (nombre) do update set region = excluded.region;
